<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario Sin título 3',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada de reCAPTCHA 2.0 no válida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta de servidor de reCAPTCHA 2.0 no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U500' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nombre Completo',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombre Completo\' es obligatorio.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Tipo de Documento',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Tipo de Documento\' es obligatorio.',
				'format' => 'El campo \'Tipo de Documento\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U483' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Número de documento',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Número de documento\' es obligatorio.'
			)
		),
		'custom_U496' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Correo electrónico',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Correo electrónico\' es obligatorio.'
			)
		),
		'custom_U479' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Contraseña',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Contraseña\' es obligatorio.'
			)
		),
		'custom_U474' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Institución educativa',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Institución educativa\' es obligatorio.'
			)
		)
	)
);

process_form($form);
?>
