<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario Sin título 6',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada de reCAPTCHA 2.0 no válida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta de servidor de reCAPTCHA 2.0 no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U718' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nombre convocatoria',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombre convocatoria\' es obligatorio.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Tema convocatoria',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Tema convocatoria\' es obligatorio.',
				'format' => 'El campo \'Tema convocatoria\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U701' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Institución educativa',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Institución educativa\' es obligatorio.'
			)
		),
		'custom_U714' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Limite de proyectos',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Limite de proyectos\' es obligatorio.'
			)
		),
		'custom_U697' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Número de jurados',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Número de jurados\' es obligatorio.'
			)
		),
		'custom_U692' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Fecha de inicio',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Fecha de inicio\' es obligatorio.'
			)
		),
		'custom_U687' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Fecha final',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Fecha final\' es obligatorio.'
			)
		),
		'custom_U682' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Ciudad',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Ciudad\' es obligatorio.'
			)
		)
	)
);

process_form($form);
?>
